# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: main
  schedule:
  - cron: "0 0 * * *"
  - cron: "0 8 * * *"
  - cron: "0 16 * * *"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Prepare git
      run: |
        git config --global user.name "mcc-devel"
        git config --global user.email "jettzheng@foxmail.com"
        git config --global user.author "mcc-devel"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --pre pip
        pip install wheel --pre
        pip install --pre fuzzywuzzy requests
    - name: Generate jsons
      run: |
        python auto-getjson.py
    - name: Clean files
      run: |
        rm -rf __pycache__
    - name: Push jsons
      run: |
        git add dd.json lc.json nt.json vu.json en.json cr.json ew.json ex.json
        git commit dd.json lc.json nt.json vu.json en.json cr.json ew.json ex.json -m "Update jsons"
        git push
